openapi: 3.0.3
info:
  title: fitness-tracker api
  description: fitness-tracker api
  version: 1.0.0
servers:
  - url: http://localhost:8081/fitnesstracker/api/v1
paths:
  /movements:
    summary: Endpoint for all things regarding movements
    get:
      operationId: return all movements
      responses:
        200:
          description: all movements
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovementDto'
    post:
      operationId: add a movement
      requestBody:
        description: The movement to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovementDto'
      responses:
        200:
          description: Saving worked!
        400:
          description: Saving failed
          content:
            application/json:
              schema:
                type: string
    put:
      operationId: change a movement
      requestBody:
        description: The movement to change
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovementDto'
      responses:
        200:
          description: Changing worked!
        400:
          description: Changing failed
          content:
            application/json:
              schema:
                type: string
  /movements/{movementId}:
    delete:
      operationId: deleting a movement
      parameters:
        - in: path
          name: movementId
          required: true
          description: id of movement
          schema:
            type: integer
      responses:
        200:
          description: Deleting worked!
        400:
          description: Deleting failed
          content:
            application/json:
              schema:
                type: string
  /movements/musclegroups:
    summary: Get all the possible muscle groups
    get:
      operationId: return all muscle groups
      responses:
        200:
          description: all muscle groups
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /workouttemplates:
    summary: endpoint for everthing workouttemplate related
    get:
      operationId: return all workouttemplates
      responses:
        200:
          description: all workouttemplates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkoutTemplateDto'
    post:
      operationId: add a workouttemplate
      requestBody:
        description: The workouttemplate to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkoutTemplateDto'
      responses:
        204:
          description: Saving worked!
        400:
          description: Saving failed
          content:
            application/json:
              schema:
                type: string
    put:
      operationId: change a workouttemplate
      requestBody:
        description: The workouttemplate to change
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkoutTemplateDto'
      responses:
        204:
          description: Changing worked!
        400:
          description: Changing failed
          content:
            application/json:
              schema:
                type: string
  /workouttemplates/{templateId}:
    delete:
      operationId: deleting a template
      parameters:
        - in: path
          name: templateId
          required: true
          description: id of template
          schema:
            type: integer
      responses:
        204:
          description: Deleting worked!
        400:
          description: Deleting failed
          content:
            application/json:
              schema:
                type: string


  /workouttemplates/workouttypes:
    summary: Get all the possible muscle groups
    get:
      operationId: return all workouttypes
      responses:
        200:
          description: all workouttypes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /workout/converttemplate/{templateId}:
    summary: Convert the workouttemplate to a new workout to be used
    get:
      operationId: Return the new workout
      parameters:
        - in: path
          name: templateId
          required: true
          description: id of template
          schema:
            type: integer
      responses:
        201:
          description: Conversion happened
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewWorkoutDto'


components:
  schemas:
    NewWorkoutDto:
      type: object
      properties:
        name:
          type: string
        movements:
          $ref: '#/components/schemas/SetRepMap'
        setInfoList:
          type: array
          items:
            $ref: '#/components/schemas/SetInfoDto'
    WorkoutTemplateDto:
      type: object
      properties:
        id:
          type: integer
        templateName:
          type: string
        setTemplates:
          type: array
          items:
            $ref: '#/components/schemas/SetTemplateDto'
    SetInfoDto:
      type: object
      properties:
        movementType:
          type: string
        amountOfTimes:
          type: integer
        orderOfSet:
          type: integer
        movement:
          $ref: '#/components/schemas/MovementDto'
    RepInfoDto:
      type: object
      properties:
        reps:
          type: integer
        weight:
          type: number
        timestamp:
          type: string
    SetRepMap:
      type: object
      properties:
        setInfo:
          type: array
          items:
            $ref: '#/components/schemas/SetInfoDto'
      required:
        - setInfo
      additionalProperties:
        type: array
        items:
          $ref: '#/components/schemas/RepInfoDto'
    SetTemplateDto:
      type: object
      properties:
        id:
          type: integer
        movementType:
          type: string
        amountOfTimes:
          type: integer
        orderOfSet:
          type: integer
        movement:
          $ref: '#/components/schemas/MovementDto'
    MovementDto:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        muscleGroup:
          type: string
