openapi: 3.0.3
info:
  title: fitness-tracker api
  description: fitness-tracker api
  version: 1.0.0
servers:
  - url: http://localhost:8081/fitnesstracker/api/v1
paths:
  /movements:
    summary: Endpoint for all things regarding movements
    get:
      operationId: return all movements
      responses:
        200:
          description: all movements
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovementDto'

components:
  schemas:
    MovementDto:
      type: object
      properties:
        name:
          type: string
  
