openapi: 3.0.3
info:
  title: fitness-tracker api
  description: fitness-tracker api
  version: 1.0.0
servers:
  - url: http://localhost:8081/fitnesstracker/api/v1
paths:
  /movements:
    summary: Endpoint for all things regarding movements
    get:
      operationId: return all movements
      responses:
        200:
          description: all movements
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovementDto'
    post:
      operationId: add a movement
      requestBody:
        description: The movement to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovementDto'
      responses:
        200:
          description: Saving worked!
        400:
          description: Saving failed
          content:
            application/json:
              schema:
                type: string
    put:
      operationId: change a movement
      requestBody:
        description: The movement to change
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovementDto'
      responses:
        200:
          description: Changing worked!
        400:
          description: Changing failed
          content:
            application/json:
              schema:
                type: string
  /movements/{movementId}:
    delete:
      operationId: deleting a movement
      parameters:
        - in: path
          name: movementId
          required: true
          description: id of movement
          schema:
            type: integer
      responses:
        200:
          description: Deleting worked!
        400:
          description: Deleting failed
          content:
            application/json:
              schema:
                type: string
  /movements/musclegroups:
    summary: Get all the possible muscle groups
    get:
      operationId: return all muscle groups
      responses:
        200:
          description: all muscle groups
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string


components:
  schemas:
    MovementDto:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        muscleGroup:
          type: string
  
